package org.randombits.confluence.conveyor.xwork;

import com.atlassian.confluence.plugin.descriptor.PluginAwareActionConfig;
import com.atlassian.plugin.Plugin;

import java.util.List;
import java.util.Map;

/**
 * Base class for action configs generated by Conveyor.
 */
public class ConveyorActionConfig extends PluginAwareActionConfig {

    public ConveyorActionConfig( String methodName, String className, Map parameters, Map results, List interceptors, Plugin plugin ) {
        super( methodName, className, parameters, results, interceptors, plugin );
    }

    public ConveyorActionConfig( String methodName, String className, Map parameters, Map results, List interceptors, List externalRefs, String packageName, Plugin plugin ) {
        super( methodName, className, parameters, results, interceptors, externalRefs, packageName, plugin );
    }
}
